# Site settings
title: Medo Hamdani's Portfolio & Blog
description: A personal website featuring code, thoughts, and books in English and Arabic.
baseurl: ""
url: "https://medohamdani.github.io"

# Multilingual Settings (New Section)
languages: ["en", "ar"] # Define the languages available
locale: "en" # Default to English

# Minimal Mistakes Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

# Jekyll Build Configuration
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Collections (Tells Jekyll about your custom post folders)
collections:
  posts_ar: # This is your Arabic posts folder
    output: true
    permalink: /:collection/:path/ # Sets the URL structure (e.g., /posts_ar/...)

defaults:
  # Posts (Default English settings)
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: true
      share: true
      lang: "en"

  # Arabic Posts (Custom settings)
  - scope:
      path: ""
      type: "posts_ar" # Applies to your Arabic folder
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: true
      share: true
      lang: "ar" # Sets the language tag
      text_direction: rtl # Essential for right-to-left layout
